### ISSUE TITLE
Point of sale system

### ISSUE THREAD

**Issue by tintinia** [abaporu-C/GROW-POS#101]
- Identify the household.
- Allow the client to create/save/print a receipt of the items purchased at a given time.
- Track the volunteer who made the sale.

**Comment by Lmarquez1983** [comment]
Comment per proffesors:
•	Prototype Two was to include some type of method for checking out a client, providing them with a receipt and storing the purchase in the member’s record. This functionality is currently not available in the application.

**Comment by abaporu-C** [comment]
Issue is too vague and it doesn't apply any longer.
