### ISSUE TITLE
Collapse opens all Cities

### ISSUE THREAD

**Issue by samjwhite** [abaporu-C/GROW-POS#106]
@Lmarquez1983  I remember you worked on this screen. Could you please take a look?

Issue: click on any City name expands ALL cities at once. 
I think the problem could be solved if you assign a unique ID for each new city .
Example: id="collapse1", id="collapse2" and so on.  See attached screenshots. 
![collapse1](https://user-images.githubusercontent.com/65174541/154301338-4cb8bb91-682d-4bcb-ba0f-5714803f6cba.jpg)
![collapse2](https://user-images.githubusercontent.com/65174541/154301344-7f2400dd-9d5f-48eb-af0b-06df016d5961.jpg)

**Comment by Lmarquez1983** [comment]
Yes, I checked on that. The collapsable that encapsulates the method is dynamic. I think is not possible to collapse each city because of this reason.
