### ISSUE TITLE
Age Report not getting percentage

### ISSUE THREAD

**Issue by abaporu-C** [abaporu-C/GROW-POS#117]
There is a bug in the age report getter that will not produce percentages and display them on the reports.
I can't seem to understand why it doesn't.

The code for it is in GROW_CRM/Controllers/Helpers/ReportsHelper from line 39 to line 67.

![Issue#1](https://user-images.githubusercontent.com/77457350/155243000-eaab7105-8f86-4e37-b3c1-2906bc48167f.png)

Here is what is happening in the reports view:

![Issue#2](https://user-images.githubusercontent.com/77457350/155243219-b40bb8e0-0327-4b07-9806-74406e64cf9a.png)

And Here:

![Issue#3](https://user-images.githubusercontent.com/77457350/155243287-5698812f-f350-4d46-9c7a-fe9a40bfde89.png)

**Comment by maikhol** [comment]
Hi I am new. Could I handle this issue?

**Comment by samjwhite** [comment]
> Hi I am new. Could I handle this issue?

Hi! Go ahead! =)
