### ISSUE TITLE
Seed Data is not working

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#12]
When I create the new migration and database, the data is not being shown when I run the application

![image](https://user-images.githubusercontent.com/90431244/152282971-0c015bed-cf3b-4de5-8072-b2e74812b236.png)

**Comment by abaporu-C** [comment]
Could you post the callstack?

What you can do is to make breakpoints and see where exactly it's not working. Here in my end it's working fine, so I don't understand what is going on.

**Comment by Lmarquez1983** [comment]
I cloned the project again. Deleted the GROW migrations folder and did the steps to add the data context, migration builder and updated database. When I run it doesn't show data at all. It doesn't show me any errors.

![image](https://user-images.githubusercontent.com/90431244/152288159-2a97c0f1-c9b0-4abd-95aa-78e06ce28a38.png)

**Comment by Lmarquez1983** [comment]
The callstack doesn't show any errors. As I said, it doesn't conflict with anything. but I don't know why is not pulling data :(

![image](https://user-images.githubusercontent.com/90431244/152289519-1a888812-5c8f-4e2f-9a75-550b1225bc89.png)

**Comment by abaporu-C** [comment]
One thing came to my mind when trying to see what is going on.

I removed the reference for concurrency from Household. If you are doing extra migrations that might be the thing causing errors when you try to seed data. 

Try to make a new migration, but don't put extra migrations. See if you can seed it then.

**Comment by Lmarquez1983** [comment]
YES! I made the migration without the extra migration and it worked!

![image](https://user-images.githubusercontent.com/90431244/152395098-3fcf96f4-f09b-40c7-8bad-5ed366d4caf2.png)
