### ISSUE TITLE
MemberDocuments UI

### ISSUE THREAD

**Issue by samjwhite** [abaporu-C/GROW-POS#128]
@Lmarquez1983 

- Change title to Member
- Fix menu item , that tiny arrow below the "Member Menu" must be on the right side (see screenshot)

![image](https://user-images.githubusercontent.com/65174541/155415002-bfe73f54-f6ec-4503-9d43-c695ebc6a34b.png)

**Comment by Lmarquez1983** [comment]
Fixed the name for Member Document Index

**Comment by Lmarquez1983** [comment]
Changed size of the nav bar items. They are normal. I will check for adding a css in order to manage sizes in case needed
