### ISSUE TITLE
Household Creation not working

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#13]
When I create the household, it shows me an error. I receive feedback in the page. However, the process doesn't complete and the dropdown lists doesn't work anymore after the error is shown

![image](https://user-images.githubusercontent.com/90431244/152283153-9de94bce-cd26-4754-b574-8a3964f1a125.png)

**Comment by abaporu-C** [comment]
I'm quite this is the same problem with the extra migrations. Make a new migration, but don't apply the extra ones.

Please, give feedback if it works.

**Comment by Lmarquez1983** [comment]
yes, you are right. Is the same problem. I am able to create household now
thanks Vin! 👍

**Comment by samjwhite** [comment]
thank you. saved lot's of time guys.
