### ISSUE TITLE
Household Code not shown in models

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#15]
I'm looking for the Household code in the model, but there is any. I guess, we gonna consider that the ID is the household code. However, is it gonna be ok when migrating the data? What will happen in that case if the primary key is created automatically but GROW has their own member id?

**Comment by abaporu-C** [comment]
Household model shouldn't be something hardcoded. It doesn't make sense in an user's perspective. For them to keep track of that is a little bit clunky. We can use the ID. Dave Kendall suggested that during our last presentation.

**Comment by Lmarquez1983** [comment]
ok great!
