### ISSUE TITLE
Household Issues

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#158]
•	When displaying Household Details, the heading should be the ‘family last name”, rather than the Household #
•	The “Search Household” button not working

**Comment by Lmarquez1983** [comment]
linked to issue #84

**Comment by gabriellemrs16** [comment]
This only displays the household number because of the seed data. When a new household is added, it is named after the family.

**Comment by gabriellemrs16** [comment]
I programmed the button to go to the Household Index page. Not sure if that's what was wanted tho

**Comment by gabriellemrs16** [comment]
@Lmarquez1983 is this still applicable?

**Comment by abaporu-C** [comment]
It is not applicable anymore. We got rid of the button and now we have some cards in the index page.
