### ISSUE TITLE
Change name of field "Custom ID"

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#160]
Why is ‘Custom ID” required? Change Custom ID to “Member Number”

![image](https://user-images.githubusercontent.com/90431244/157502521-951655e0-cb13-436b-9722-a6a03d110306.png)

**Comment by Lmarquez1983** [comment]
comments per mark:
•	What is a custom ID? Why not just call it new member/Household ID? And why not auto generate it with the option to override?

**Comment by gabriellemrs16** [comment]
@Lmarquez1983 do you want me to change something else in this, or just change CustomID to say Member Number?

**Comment by Lmarquez1983** [comment]
No, it's just changing the name. I think it should be something like Member ID and in the tooltip add something like: "Use in case a specific ID number is needed"

**Comment by gabriellemrs16** [comment]
Okay sounds good

**Comment by gabriellemrs16** [comment]
Done
