### ISSUE TITLE
Member/Create household dropdown not populated

### ISSUE THREAD

**Issue by samjwhite** [abaporu-C/GROW-POS#17]
Nothing to choose from household dropdown. 
Attempt to create gives an error "missing required foreign key
![Screenshot 2022-02-03 163222](https://user-images.githubusercontent.com/65174541/152432654-d1ee8844-219c-4b8d-9df8-915e7fa05c65.jpg)
"

**Comment by samjwhite** [comment]
After further investigation I found that the model Members was edited. Now we need to update controller with new fields. Same for Views

**Comment by samjwhite** [comment]
Now , create is fixed. Edit doesn't work properly, YearlyIncome does not update, neither displays error message

**Comment by abaporu-C** [comment]
> Now , create is fixed. Edit doesn't work properly, YearlyIncome does not update, neither displays error message

I'll check on this!

**Comment by abaporu-C** [comment]
About the member create page, I think we should just drop it all together. The idea of the master detail page is that members would be created and managed directly on the household page.

In this way we don't need to make a customer deal with composite keys, or a ddl with 500+ items

**Comment by samjwhite** [comment]
problem fixed. Merging branch 17 with main
