### ISSUE TITLE
[P2] - Items list error in Unique Key

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#171]
Inventory allows the user to enter the same item more than once. For example, I’ve added “Bananas”, item number 104 twice. 

![image](https://user-images.githubusercontent.com/90431244/157511767-e894125c-a9d4-423f-8b0a-0c1394ba39a1.png)

**Comment by Lmarquez1983** [comment]
Additional comments on items list:

•	Why is there an asterisk beside some names? What does it indicate?


![image](https://user-images.githubusercontent.com/90431244/157513203-cc37c7a0-393f-4de0-a5f5-b68870e18edd.png)

**Comment by gabriellemrs16** [comment]
The asterisks mean that there's a limit

**Comment by Lmarquez1983** [comment]
We need to take them out. If they need to add a limit, we may need to come with another kind of solution

**Comment by gabriellemrs16** [comment]
Done

**Comment by Lmarquez1983** [comment]
asterisks after the names are still showing
