### ISSUE TITLE
[create item] - P2 - Items

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#197]
When creating a new item, it asks for the id. This should be generated automatically. It also accepts any word or number. Are we gonna keep it like that? or we are going to handle just ints?

![image](https://user-images.githubusercontent.com/90431244/158433885-f6e1b604-b2df-4423-a3ca-4cce0840611c.png)

**Comment by abaporu-C** [comment]
Well, it looks like it won't be done.

**Comment by gabriellemrs16** [comment]
@abaporu-C I can do it later today, if you'd like :)

**Comment by gabriellemrs16** [comment]
@abaporu-C @Lmarquez1983 I changed the item code from string to int. Is that okay? It restricts new codes from being anything. It has to be a number now.

**Comment by abaporu-C** [comment]
Closed with pull request #346
