### ISSUE TITLE
New Order search household.

### ISSUE THREAD

**Issue by samjwhite** [abaporu-C/GROW-POS#249]
@gabriellemrs16  @Hare-J 
Improve household search. 
Remember that end user and members do not remember Household ID. 
Search by household name, member name (link to member's household), street name etc.
 
![image](https://user-images.githubusercontent.com/65174541/160856377-818744f7-0971-4e13-8136-253a91e6d841.png)

**Comment by gabriellemrs16** [comment]
@samjwhite Dave Kendall specifically requested the household number. He said that the house member will have an ID card that the volunteer will use to find them in the system. Or else I would have put 2 ddls

**Comment by abaporu-C** [comment]
Could we add an option? Like, either type household ID or Name?

**Comment by gabriellemrs16** [comment]
@abaporu-C like a radio button or something of sorts?

**Comment by abaporu-C** [comment]
That works. 

But because Dave asked specifically for Household ID, I think we can add that later.

**Comment by gabriellemrs16** [comment]
Connected to Issue #308

**Comment by abaporu-C** [comment]
Closed with pull request #345
