### ISSUE TITLE
Order Creation - Select HouseholdID change to Household Name

### ISSUE THREAD

**Issue by Hare-J** [abaporu-C/GROW-POS#308]
It seems that instead of manually entering the ID of a household when starting to place an order, we should have a DDL or other such control to enable us to select a household by name.

**EDIT** Dave suggested that we create an "autocomplete box" for this instead, but a DDL is still acceptable.

**Comment by gabriellemrs16** [comment]
https://stackoverflow.com/questions/37585676/autocomplete-dropdown-in-mvc5

**Comment by abaporu-C** [comment]
Closed with pull request #345
