### ISSUE TITLE
"Illnesses Accredited" Poor Word Choice

### ISSUE THREAD

**Issue by Hare-J** [abaporu-C/GROW-POS#312]
We were advised to change this to "Medical History" or "Illnesses Reported" or something along those lines for member creation. Accredited just doesn't make sense given the context.

**Comment by Hare-J** [comment]
Done 

PS I realize this probably should've just gone with the illnesses/concerns box placement, sorry about that.

**Comment by abaporu-C** [comment]
Closed with pull request #334
