### ISSUE TITLE
Remove "House" From Seed Data for Households

### ISSUE THREAD

**Issue by Hare-J** [abaporu-C/GROW-POS#314]
Alternatively, enforce rules and guidance for users inputting a house so that **every** house is "House X". Make sure household names are made consistent. 

"Need to work on the way names are entered. All your seed data places the word “house’ in front of the last name. I entered one with just a last name. Need to work on enforcing consistency in the names. Provide guidance to the user. " - Dave Kendell

**Comment by samjwhite** [comment]
Added prepend House: to guide used. 
In HouseholdsController/Create ---> all new houses will have prepend "House " if user adds a custom name. Else there will be an ID number

![image](https://user-images.githubusercontent.com/65174541/162638940-70ff292c-ad25-4dac-b2b2-45f0c6f18514.png)
