### ISSUE TITLE
POS/Orders Minor Changes

### ISSUE THREAD

**Issue by Hare-J** [abaporu-C/GROW-POS#320]
Dave has suggested that we: 

- Change '+' button to "Add Item"
- Change the button to add a new item from "Create" to "Add"
- Change "Create" to "Checkout" when completing the order form
- Receipt button needs to be fixed, see [Issue #305](https://github.com/abaporu-C/GROW-POS/issues/305)
- Move Payment Method from the top right down below or beside the table of items in the order. Current placement is inconsistent with [_Jakob's Law_](https://www.zorraquino.com/en/dictionary/ux/what-is-jakobs-law.html)
- Make quantity of item added 1 by default

**Comment by gabriellemrs16** [comment]
Done - receipt button fix will be part of said issue
