### ISSUE TITLE
Lots of Minor Issues with Households

### ISSUE THREAD

**Issue by Hare-J** [abaporu-C/GROW-POS#321]
Directly from Dave's feedback:

~~- Search by “Name” not working correctly, all names displayed in search results (See [Issue #313](https://github.com/abaporu-C/GROW-POS/issues/313))~~

~~- Why is “House” in front of every name? (See [Issue #315](https://github.com/abaporu-C/GROW-POS/issues/315))~~

~~Why does LICO verified look like a clickable button?~~

~~Why does a “member” page have “Details for Household House Ruecker” at the top of the page?~~  

- Custom ID button still needs a help for explanation. 

~~- Filter search by household name doesn’t work. Created a new household and then tried to search for it using filter and the filter doesn’t appear to work. Other filter options (ID for example) appear to work. (See [Issue #313](https://github.com/abaporu-C/GROW-POS/issues/313)?)~~

~~Need to work on the way names are entered. All your seed data places the word “house’ in front of the last name. I entered one with just a last name. Need to work on enforcing consistency in the names. Provide guidance to the user.~~

**Comment by samjwhite** [comment]
#313 fixed

**Comment by samjwhite** [comment]
#314 and #315 describe same issue. 
Fixed with automatic prepend "House "

**Comment by samjwhite** [comment]
all done. Custom ID button has separate issue open
