### ISSUE TITLE
Annotation for household member (check for entity in model giving feedback information)

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#35]
When creating a member for a household and not providing any information, it jumps to error. We need to check on the data annotations for the required fields giving the proper feedback

![image](https://user-images.githubusercontent.com/90431244/152713906-b15d0dae-bf93-4066-9fe0-07e4703c9b3c.png)

**Comment by abaporu-C** [comment]
Already fixed it on issue #23
