### ISSUE TITLE
Set default province to Ontario

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#64]
In the household creation, Ontario should be as the default province.

**Comment by samjwhite** [comment]
Done. 
In case someone comes across here is the solution 

private SelectList ProvinceSelectList(int? selectedId)
        {
            return new SelectList(_context.Provinces

                .OrderByDescending(d => d.Name == "Ontario")
                .ThenBy(d => d.Name), "ID", "Name", selectedId);
        }
