### ISSUE TITLE
checkbox for no fixed address

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#69]
No fixed address – add a method to handle this but need to enable checking of the address if the box isn’t checked and no validation if it is checked; default to GROWs address; each person still gets a unique household number; when they click the no fixed address, populate GROWs address and save.

![1](https://user-images.githubusercontent.com/90431244/153450511-a4fdf992-ee03-409f-aa67-08a10b64670c.png)

**Comment by abaporu-C** [comment]
Already Fixed with previous pull request
