### ISSUE TITLE
Add field for "Other" income situation when selected from DDL

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#73]
Income situation: Choose “other” and add a different income situation.
![5](https://user-images.githubusercontent.com/90431244/153463096-3ee54908-3710-431f-8ee3-6cb628bf699f.png)

**Comment by samjwhite** [comment]
solved. 
missed one line in Scripts section
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
