### ISSUE TITLE
Postal Code property should accept lower case and no spaces

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#80]
All Postal Codes should be formatted correctly with upper case letter and a space in between L3C 0A8 after the user input

**Comment by samjwhite** [comment]
Done. 
It is not exactly as good as it could be, but works,
@Lmarquez1983  please test (create, edit), and tell you opinion. 
Also note that there is a rule applied 

Disallows:

Z2T 1B8 (leading Z)
H2T 1O3 (contains O)
Leading Z,W or to contain D, F, I, O, Q or U
