### ISSUE TITLE
Changes to Memberships (Household page)

### ISSUE THREAD

**Issue by Lmarquez1983** [abaporu-C/GROW-POS#85]
Memberships
o	Have just the numbers no names in the members total list.
o	Seed data still not useful/meaningful. – more seed data
![12](https://user-images.githubusercontent.com/90431244/153488220-66f04dda-6b14-4c86-84f0-d5d329f57337.png)

**Comment by samjwhite** [comment]
> Memberships
> o Have just the numbers no names in the members total list.

this part done. 
Working on **seed data**

**Comment by Lmarquez1983** [comment]
comment per Mark:

•	Replace the notes sections filled with meat to something more useful. Improve seed data to better show off your functionality.

**Comment by samjwhite** [comment]
complete
