### ISSUE TITLE
Add guides to required fields. 

### ISSUE THREAD

**Issue by samjwhite** [abaporu-C/GROW-POS#97]
This is a monotonous job, but has to be done to improve UI. 
Steps: 
1. Open the model
2. Check which fields have [Required] annotation
3. Go to Views and on each page where we have inputs add black astrixes (*) at the end of title. (Create, Edit, Update, Add)
![add guides to required inputs](https://user-images.githubusercontent.com/65174541/153612164-1b634052-081f-44ca-b5f4-9ebd96af2522.jpg)

**Comment by abaporu-C** [comment]
Closed with pull request #147
